### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by 3eeesh** [SM-FREE-TOOLS/-Telegram-Adder-Scraper-Members-NEW-FREE-2024#10]
Hi

When I try to log in, I put in my number then click enter, then I get the below error. 

`Traceback (most recent call last):
  File "main1.713.py", line 1436, in <module>
  File "C:\Users\oh_3e\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\oh_3e\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oh_3e\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "main1.713.py", line 323, in main
  File "C:\Users\oh_3e\AppData\Local\Programs\Python\Python312\Lib\site-packages\telethon\client\auth.py", line 657, in __aenter__
    return await self.start()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\oh_3e\AppData\Local\Programs\Python\Python312\Lib\site-packages\telethon\client\auth.py", line 184, in _start
    await self.send_code_request(phone, force_sms=force_sms)
  File "C:\Users\oh_3e\AppData\Local\Programs\Python\Python312\Lib\site-packages\telethon\client\auth.py", line 434, in send_code_request
    result = await self(functions.auth.SendCodeRequest(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oh_3e\AppData\Local\Programs\Python\Python312\Lib\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oh_3e\AppData\Local\Programs\Python\Python312\Lib\site-packages\telethon\client\users.py", line 87, in _call
    result = await future
             ^^^^^^^^^^^^
telethon.errors.rpcerrorlist.ApiIdInvalidError: The api_id/api_hash combination is invalid (caused by SendCodeRequest)`

**Comment by SM-FREE-TOOLS** [comment]
Make sure to create your own API ID and HASH, after that type it into credentials.txt
Check the format in the credentials example file.
