### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by maaxx3388** [SM-FREE-TOOLS/-Telegram-Adder-Scraper-Members-NEW-FREE-2024#5]
Traceback (most recent call last):
  File "main1.704.py", line 1436, in <module>
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "main1.704.py", line 166, in main
IndexError: list index out of range

**Comment by SM-FREE-TOOLS** [comment]
Check your api id and hash in the credentials file. Make sure that it is also written in the correct format. Check the format in the credentials example file.
