### ISSUE TITLE
Line 166 Error

### ISSUE THREAD

**Issue by CommunityGraveyard** [SM-FREE-TOOLS/-Telegram-Adder-Scraper-Members-NEW-FREE-2024#6]
Traceback (most recent call last):
  File "main1.707.py", line 1436, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "main1.707.py", line 166, in main
IndexError: list index out of range

**Comment by SM-FREE-TOOLS** [comment]
Check your api id and hash in the credentials file. Make sure that it is also written in the correct format. Check the format in the credentials example file.

**Comment by CommunityGraveyard** [comment]
Its the same

22222222,"87687678686786688768768"

In that format.
